### ISSUE TITLE
5.5.5 update

### ISSUE THREAD

**Issue by adrienrichmond** [Hartie95/sysdvr-overlay#2]
Allow operation on the recently released version 5.5.5
Thanks for your work ^^

**Comment by Hartie95** [comment]
Release for 5.5.5 is out:
https://github.com/Hartie95/sysdvr-overlay/releases/tag/1.0.9

Change needed for it were already pushed though, but I didn't get to test them until now. 
In the future it should be possible to use the builds from the github actions in these cases, until I make a full release.
