### ISSUE TITLE
Mini lag during stream 

### ISSUE THREAD

**Issue by adrienrichmond** [Hartie95/sysdvr-overlay#3]
Hello, I am using your tool to retransmit it on OBS.  The 720p does not bother me but however during the stream I sometimes encounter mini image freezes with a sound jerk.  what to do ?  THANKS

**Comment by Hartie95** [comment]
It's not really part of the overlay, so this is the wrong place, the sysdvrs devs discord might be a better place. 

But depending on the connection and game, increasing the cpu clock via sys-clk can help. 
I nor all have the cpu on the second highest frequency most of the time.
