### ISSUE TITLE
Crash atmosphere

### ISSUE THREAD

**Issue by adrienrichmond** [Hartie95/sysdvr-overlay#4]
When I disable or enable USB or Wireless 3 times, the CFW Atmoshere crashes

Error code : 2001-0114(Oxe401) 
Program : 00FF0000A53BB665

**Comment by adrienrichmond** [comment]
same problem

**Comment by Hartie95** [comment]
I can replicate it, but the same also seems to happen when using the official sysdvr tool, just that you need to open and close the application a few time via save and exit, to actually apply the change.
The program ID is also the one from the sys-dvr system module, so not the tesla overlay my overlay runs in.

So best report this over at the [sysdvr github](https://github.com/exelix11/SysDVR/issues)
